# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = fieldbus_intro
SUB_SRC_FILES = \
    glossary.xml \
    preface.xml \
    ch01_fieldbus_basic.xml \
    ch02_fieldbus_specs.xml \
    ch03_fieldbus_features.xml \
    ch04_fieldbus_common.xml \
    appendix.xml \
    reference.xml

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk